# Site settings
title: ArqEngX
email: arqengx@gmail.com
description: >
  Arqengx - Planejamento, controle e soluções.
baseurl: ""
url: "http://arqengx.github.io"
github_username:  arqengx
repository: arqengx

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
